---
- name: Run roles and SCAP audit
  hosts: all
  remote_user: DunAdmin
  become: true
  roles:
    - redHat_official_minAnssi
    - scap-install
    - scap-scan

# ---
# - name: Run roles and SCAP audit
#   hosts: dunb13-VM
#   remote_user: DunAdmin
#   become: yes # true
#   # roles:
#   #   - RedHatOfficial.rhel8_anssi_bp28_minimal
#   # tasks:
#     - name: Install SCAP
#       yum:
#         name:
#           - openscap-scanner
#           - scap-security-guide
#         state: present

#     - name: Run SCAP audit with ANSSI profile
#       command:
#         cmd: >-
#             oscap xccdf eval
#             --profile xccdf_org.ssgproject.content_profile_anssi_bp28_minimal
#             --results /tmp/anssi_results.xml
#             --report /tmp/anssi_report.html
#             /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
#       register: oscap_result
#       ignore_errors: true

#     - name: Save audit report
#       fetch:
#         src: /tmp/anssi_report.html
#         dest: ./audit_reports/audit_report.xml
#         flat: yes
#       tags:
#         - verification