---
- name: Run roles and SCAP audit
  hosts: all
  remote_user: DunAdmin
  become: true
  roles:
    # - role: ./roles/redHat_official_minAnssi
    - role : ./roles/scap-install
    - role : ./roles/dnf-auto
    - role : ./roles/gpg-check
    - role : ./roles/pam-all
    - role : ./roles/authselect
    - role : ./roles/pwd-spec
    - role : ./roles/pwd-reuse
    - role : ./roles/scap-scan